version: '3.7'

services:
  database:
    image: mysql
    container_name: dev-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: admin_user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_HOST: '%'